import { submissions } from '@shared/schema';
import type { Submission, InsertSubmission } from '@shared/schema';
import { drizzle } from "drizzle-orm/better-sqlite3";
import Database from "better-sqlite3";
import { eq, desc } from "drizzle-orm";

const DB_PATH = process.env.DATABASE_PATH || "data.db";
const sqlite = new Database(DB_PATH);
sqlite.pragma("journal_mode = WAL");

// Create the submissions table on first boot if Drizzle migrations haven't run.
sqlite.exec(`
  CREATE TABLE IF NOT EXISTS submissions (
    id TEXT PRIMARY KEY,
    client TEXT NOT NULL,
    role TEXT NOT NULL,
    candidate_name TEXT NOT NULL,
    candidate_email TEXT NOT NULL,
    candidate_mobile TEXT NOT NULL,
    timezone TEXT NOT NULL,
    proctor TEXT DEFAULT '',
    attestation INTEGER NOT NULL,
    submitted_at TEXT NOT NULL,
    section_b TEXT NOT NULL,
    section_c TEXT NOT NULL,
    email_status TEXT DEFAULT 'pending',
    email_error TEXT DEFAULT '',
    download_token TEXT DEFAULT '',
    timer_started_at TEXT DEFAULT '',
    elapsed_seconds INTEGER DEFAULT 0,
    invite_token TEXT DEFAULT ''
  );
`);

// Invites table — one-time-use links generated by Resonance Asia staff.
sqlite.exec(`
  CREATE TABLE IF NOT EXISTS invites (
    token TEXT PRIMARY KEY,
    candidate_name TEXT NOT NULL,
    candidate_email TEXT NOT NULL,
    role TEXT NOT NULL,
    client TEXT NOT NULL,
    proctor TEXT DEFAULT '',
    created_at TEXT NOT NULL,
    created_by TEXT DEFAULT '',
    expires_at TEXT NOT NULL,
    submitted_at TEXT DEFAULT '',
    submission_id TEXT DEFAULT ''
  );
`);

// SQLite-safe migrations for columns added after the original schema.
try {
  const cols = sqlite.prepare(`PRAGMA table_info(submissions)`).all() as { name: string }[];
  const has = (n: string) => cols.some((c) => c.name === n);
  if (!has("download_token")) {
    sqlite.exec(`ALTER TABLE submissions ADD COLUMN download_token TEXT DEFAULT ''`);
  }
  if (!has("timer_started_at")) {
    sqlite.exec(`ALTER TABLE submissions ADD COLUMN timer_started_at TEXT DEFAULT ''`);
  }
  if (!has("elapsed_seconds")) {
    sqlite.exec(`ALTER TABLE submissions ADD COLUMN elapsed_seconds INTEGER DEFAULT 0`);
  }
  if (!has("invite_token")) {
    sqlite.exec(`ALTER TABLE submissions ADD COLUMN invite_token TEXT DEFAULT ''`);
  }
  if (!has("candidate_surname")) {
    sqlite.exec(`ALTER TABLE submissions ADD COLUMN candidate_surname TEXT DEFAULT ''`);
  }
} catch (_) {
  // best-effort
}

// ---- Invite helpers (raw SQLite — independent of drizzle schema) ----

export interface InviteRow {
  token: string;
  candidateName: string;
  candidateEmail: string;
  role: string;
  client: string;
  proctor: string;
  createdAt: string;
  createdBy: string;
  expiresAt: string;
  submittedAt: string;
  submissionId: string;
}

function rowToInvite(r: any): InviteRow {
  return {
    token: r.token,
    candidateName: r.candidate_name,
    candidateEmail: r.candidate_email,
    role: r.role,
    client: r.client,
    proctor: r.proctor ?? "",
    createdAt: r.created_at,
    createdBy: r.created_by ?? "",
    expiresAt: r.expires_at,
    submittedAt: r.submitted_at ?? "",
    submissionId: r.submission_id ?? "",
  };
}

export const inviteStore = {
  create(input: {
    token: string;
    candidateName: string;
    candidateEmail: string;
    role: string;
    client: string;
    proctor?: string;
    createdBy?: string;
    expiresAt: string;
  }): InviteRow {
    const createdAt = new Date().toISOString();
    sqlite
      .prepare(
        `INSERT INTO invites (token, candidate_name, candidate_email, role, client, proctor, created_at, created_by, expires_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`
      )
      .run(
        input.token,
        input.candidateName,
        input.candidateEmail,
        input.role,
        input.client,
        input.proctor ?? "",
        createdAt,
        input.createdBy ?? "",
        input.expiresAt
      );
    return inviteStore.get(input.token)!;
  },
  get(token: string): InviteRow | null {
    const r = sqlite.prepare(`SELECT * FROM invites WHERE token = ?`).get(token) as any;
    return r ? rowToInvite(r) : null;
  },
  markUsed(token: string, submissionId: string): void {
    sqlite
      .prepare(
        `UPDATE invites SET submitted_at = ?, submission_id = ? WHERE token = ?`
      )
      .run(new Date().toISOString(), submissionId, token);
  },
  list(limit = 100): InviteRow[] {
    return (
      sqlite
        .prepare(`SELECT * FROM invites ORDER BY created_at DESC LIMIT ?`)
        .all(limit) as any[]
    ).map(rowToInvite);
  },
};

export const db = drizzle(sqlite);

export type CreateSubmissionInput = InsertSubmission & {
  id: string;
  submittedAt: string;
  downloadToken: string;
  timerStartedAt?: string;
  elapsedSeconds?: number;
};

export interface IStorage {
  createSubmission(input: CreateSubmissionInput): Promise<Submission>;
  getSubmission(id: string): Promise<Submission | undefined>;
  listSubmissions(limit?: number): Promise<Submission[]>;
  updateEmailStatus(id: string, status: "sent" | "failed", error?: string): Promise<void>;
  countToday(): number;
}

export class DatabaseStorage implements IStorage {
  async createSubmission(
    input: CreateSubmissionInput
  ): Promise<Submission> {
    return db.insert(submissions).values(input).returning().get();
  }

  async getSubmission(id: string): Promise<Submission | undefined> {
    return db.select().from(submissions).where(eq(submissions.id, id)).get();
  }

  async listSubmissions(limit = 50): Promise<Submission[]> {
    return db.select().from(submissions).orderBy(desc(submissions.submittedAt)).limit(limit).all();
  }

  async updateEmailStatus(id: string, status: "sent" | "failed", error = "") {
    db.update(submissions)
      .set({ emailStatus: status, emailError: error })
      .where(eq(submissions.id, id))
      .run();
  }

  countToday(): number {
    const today = new Date().toISOString().slice(0, 10); // YYYY-MM-DD
    const row = sqlite
      .prepare(
        `SELECT COUNT(*) as n FROM submissions WHERE substr(submitted_at,1,10) = ?`
      )
      .get(today) as { n: number } | undefined;
    return row?.n ?? 0;
  }
}

export const storage = new DatabaseStorage();
